version: "3.3"

services:
  web:
    build:
      context: ./backend
    volumes:
      - ./backend:/code
      - staticfiles:/code/static
      - ./backend/media:/code/media
      - mediafiles:/code/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG="false"
  frontend:
    build: ./frontend
    volumes:
      - front:/code/build/

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - front:/var/www/amlschool/frontend
      - staticfiles:/var/www/amlschool/statics
      - mediafiles:/var/www/amlschool/media
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/Aml-school.com/cert.pem:/etc/ssl/private/cert.pem
      - /etc/letsencrypt/live/Aml-school.com/privkey.pem:/etc/ssl/private/privkey.pem

    depends_on:
      - frontend
      - web

volumes:
  staticfiles:
  mediafiles:
  front:
